version: 1.0.0-beta.{build}

# Fix line endings in Windows. (runs before repo cloning)
init:
  - git config --global core.autocrlf input

# this turns of AppVeyor automatic searching for test-assemblies, not the actual testing
test_script:
  # - dnx MessageTemplates.Tests test
  - packages\xunit.runner.console\tools\xunit.console.x86.exe FsMessageTemplates.Tests\bin\Release\FsMessageTemplates.Tests.dll
  - vstest.console /Logger:AppVeyor MessageTemplates.PerfTests\bin\Release\MessageTemplates.PerfTests.exe
  - fsiAnyCPU -O --tailcalls+ --crossoptimize+ --exec MessageTemplates.PerfTests\Script.fsx --exportCharts
  - fsiAnyCPU -O --tailcalls+ --crossoptimize+ --exec MessageTemplates.PerfTests\PerfTests.fsx --exportCharts

configuration: Release
os: Visual Studio 2015
platform: Any CPU
install:
  - set PATH=%PROGRAMFILES(x86)%\MSBuild\14.0\Bin;%PROGRAMFILES(x86)%\Microsoft SDKs\F#\4.0\Framework\v4.0\;%PATH%
  - dnvm upgrade -alias default
  - .paket\paket.exe restore
  - dnu restore MessageTemplates
  - dnu restore MessageTemplates.Tests
  - set DNX_BUILD_VERSION=%APPVEYOR_BUILD_NUMBER%
build:
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true
  parallel: true

artifacts:
- path: artifacts\bin\MessageTemplates\$(configuration)\*.nupkg
- path: FsMessageTemplates\bin\Release\FsMessageTemplates.*
- path: artifacts\perfcharts\*.png
