version: 1.0.{build}
configuration: Release
os: Visual Studio 2015
platform: Any CPU
install:
  - set PATH=%PROGRAMFILES(x86)%\MSBuild\14.0\Bin;%PATH%
  - nuget restore MessageTemplates.sln
  - dnu restore MessageTemplates
  - dnu restore MessagetTemplates.Tests
build:
  verbosity: minimal
  project: MessageTemplates.sln
  publish_nuget: true
  publish_nuget_symbols: true
