version: 1.0.{build}
configuration: Release
platform: Any CPU
install:
  - set PATH=%PROGRAMFILES(x86)%\MSBuild\14.0\Bin;%PATH%
  - dnvm install latest -Unstable -Persistent
  - nuget restore
  - dnu restore MessageTemplates
  - dnu restore MessagetTemplates.Tests
build:
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true
