version: 1.0.{build}
os: Visual Studio 2015 RC
configuration: Release
platform: Any CPU
environment:
  DNX_FEED: https://www.nuget.org/api/v2
install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- dnvm install latest
before_build:
- nuget restore MessageTemplates.sln
build:
  project: MessageTemplates.sln
  publish_nuget: true
  publish_nuget_symbols: true
  parallel: true
  verbosity: minimal
