version: 1.0.{build}
configuration: Release
platform: Any CPU
os: Visual Studio 2015 RC
environment:
  VisualStudioVersion: 14.0
  DNX_FEED: https://www.nuget.org/api/v2
install:
  - set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
  - dnvm install 1.0.0-beta5
  - dnu restore
build:
  verbosity: normal
  project: MessageTemplates.sln
  publish_nuget: true
  publish_nuget_symbols: true
