version: 1.0.0-beta.{build}
configuration: Release
os: Visual Studio 2015
platform: Any CPU
install:
  - set PATH=%PROGRAMFILES(x86)%\MSBuild\14.0\Bin;%PATH%
  - dnvm install latest -Persistent
  - nuget restore
  - dnu restore MessageTemplates
  - dnu restore MessageTemplates.Tests
  - set DNX_BUILD_VERSION=%APPVEYOR_BUILD_NUMBER%
build:
  verbosity: minimal
  publish_nuget: true
  publish_nuget_symbols: true
