version: 1.0.{build}
configuration: Release
os: Unstable
platform: Any CPU
install:
  - nuget restore MessageTemplates.sln
build:
  verbosity: normal
  project: MessageTemplates.sln
  publish_nuget: true
  publish_nuget_symbols: true
