version: 1.0.{build}
os: Visual Studio 2015 RC
configuration: Release
platform: Any CPU

install:
- set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- powershell -NoProfile -ExecutionPolicy unrestricted -Command "&{iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.ps1'))}"
- dnvm list
- dnvm install latest
before_build:
- nuget restore MessageTemplates.sln
build:
  project: MessageTemplates.sln
  publish_nuget: true
  publish_nuget_symbols: true
